### ISSUE TITLE
ЭТО БРАВО!!!

### ISSUE THREAD

**Issue by ffdown** [AlekPet/Fooocus_Extensions_AlekPet#1]
Восхищению сей оперативности, у меня прям слов благодарности таковых не найдётся!

**Comment by ffdown** [comment]
Ещё с а1111 тащусь с твоего расширения, очень странно что так мало народу о нём знало, рекламил везде где только мог! Ибо простота и действенность, а что нам ещё надо))! Прям топчик!

**Comment by AlekPet** [comment]
> Ещё с а1111 тащусь с твоего расширения, очень странно что так мало народу о нём знало, рекламил везде где только мог! Ибо простота и действенность, а что нам ещё надо))! Прям топчик!

Тут меня еще раньше подключить оффлайн переводчик в comflyui (в процессе), если руки дойдут и сюда закину, чтобы без интернета можно было переводить.

**Comment by ffdown** [comment]
> > Ещё с а1111 тащусь с твоего расширения, очень странно что так мало народу о нём знало, рекламил везде где только мог! Ибо простота и действенность, а что нам ещё надо))! Прям топчик!
> 
> Тут меня еще раньше просили подключить оффлайн переводчик к comflyui (в процессе), если руки дойдут и сюда закину, чтобы без интернета можно было переводить.

а что и так можно??? я уж думал без инета сейчас нифигась не пашет. Есть кстати такая штукень как REVERSO и вот что мне в ней прям люто греет, это то что она ещё и не один вариант перевода даёт, а несколько, в различном контексте.. типа синонимы можно хитрозадые откапывать. Если на его основе что-то замутить то оно и "one bbutton prompt" подвинет =)

**Comment by AlekPet** [comment]
> > > Ещё с а1111 тащусь с твоего расширения, очень странно что так мало народу о нём знало, рекламил везде где только мог! Ибо простота и действенность, а что нам ещё надо))! Прям топчик!
> > 
> > 
> > Тут меня еще раньше просили подключить оффлайн переводчик к comflyui (в процессе), если руки дойдут и сюда закину, чтобы без интернета можно было переводить.
> 
> а что и так можно??? я уж думал без инета сейчас нифигась не пашет. Есть кстати такая штукень как REVERSO и вот что мне в ней прям люто греет, это то что она ещё и не один вариант перевода даёт, а несколько, в различном контексте.. типа синонимы можно хитрозадые откапывать. Если на его основе что-то замутить то оно и "one bbutton prompt" подвинет =)

Взял себе на заметку 😉
