### ISSUE TITLE
Create pull request

### ISSUE THREAD

**Issue by Irmagon** [AlekPet/Fooocus_Extensions_AlekPet#3]
Maybe send this as pull request in Fooocus branch?

**Comment by AlekPet** [comment]
> Maybe send this as pull request in Fooocus branch?

Possibly, but I doubt they will add it. https://github.com/lllyasviel/Fooocus/issues/667

**Comment by mashb1t** [comment]
There might be a misunderstanding. Extensions, like in A1111 or ComfyUI, are not supported by Fooocus, as it's not built with modularity in mind, but you can always create a PR with your changes based on a fork.
