### ISSUE TITLE
can use bing translator?

### ISSUE THREAD

**Issue by andyhebear** [AlekPet/Fooocus_Extensions_AlekPet#4]
can use bing translator?

**Comment by AlekPet** [comment]
> can use bing translator?

Hi. To use bing (Microsoft Translator), you need an api key, and add it to your config.json file.  https://pypi.org/project/deep-translator/#microsoft-translator-1

**Comment by AlekPet** [comment]
> can use bing translator?

Sorry, I was wrong, I thought this was a comfyui repository, but this is fooocus, only google is used here.

**Comment by AlekPet** [comment]
Update extension, add support select other service for translate prompts https://github.com/AlekPet/Fooocus_Extensions_AlekPet/tree/main/prompt_translate#description
